- name: Create Auto Scaling Group
  ec2_autoscaling_group:
    name: PgBouncerASG
    launch_template:
      name: PgBouncerLaunchTemplate
    min_size: 2
    max_size: 6
    desired_capacity: 2
    vpc_zone_identifier:
      - subnet-abcdef1
      - subnet-abcdef2
    health_check_type: EC2
    wait_for_instances: yes
