- name: Launch EC2 instances
  ec2_instance:
    key_name: my-key
    instance_type: t3.small
    image_id: ami-12345678
    region: "{{ region }}"
    vpc_subnet_id: subnet-abcdef
    security_group: sg-123456
    tags:
      Name: PgBouncerInstance
